### ISSUE TITLE
Preparation for series A funding - research competitors 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/series-a#10] opened 2024-01-09 10:12 UTC
VCs will research competitors before investing so we should be prepared.

One of the competitors

>Enhancing the sustainability of open-source software
The tea Protocol is a decentralized technology framework secured by reputation and incentives that enables open-source developers & maintainers to be rewarded for their software contributions.
https://tea.xyz/learn/overview

>The ranking algorithm for open-source software
Proof of Contribution measures the value, position, and impact of open-source software projects. The ranking algorithm is engineered to bring fairness and equitable rewards to the OSS ecosystem.
https://tea.xyz/learn/proof-of-contribution

https://github.com/teaxyz 3K followers, no Open Source code

Useful links
https://tea.xyz/oss-dev/how-does-it-work 
https://tea.xyz/learn/roadmap

**Comment by 0x4007** [comment] 2024-01-29 07:50
This is pretty insane. Good find.

### Strengths (what they have over us)

- The creator of [homebrew](https://brew.sh/) is the main guy behind this.

> tea tasters, typically, are experienced software developers willing to dedicate some of their time to check the claims associated with a package (functionality, security, [semantic versioning](https://semver.org/), license accuracy, etc.) and stake both their reputation and TEA tokens to demonstrate the outcome of their research and support their reviews. In the tea Protocol, “staking your tea” is the process of locking TEA tokens to support your reviews, potentially earning rewards or facing penalties based on the consensus about the quality of your reviews.

- This is a cool idea we've discussed in passing, where we have contributors stake tokens to boost rewards etc. It makes sense to lift this idea specifically for our XP system. Stake UBQ on some contribution and boost XP output if it is accepted (or lose UBQ if it is not?)

### Weaknesses

> Package maintainers will register their projects with a registry powered by a Byzantine fault-tolerant blockchain

- Making their own L1 imo is not a good idea. It requires redundant labor. We can rely on existing infrastructure on Ethereum/Gnosis Chain etc. edit: it is only for non financial purposes. They are saving records around open source software dependency trees.

- Their rewards system seems to be limited to minting the Tea token. However we are offering our own USD denominated banking solution with our stablecoin and cards. This should allow us easier direct access to revenue, while allowing developers to get paid cash equivalents to contribute to open source.

- We offer comment incentives, which allows us to compensate the development of open source software in a more comprehensive way (not just code, but also the research and communication/collaboration around producing the code)

### Fundamental Differences

- It seems that they are more focused on the community paying the developer teams, where we are doing the opposite (developer teams paying community for contributions.) Technically speaking we can use our system for both purposes, but the project would just need to ask for donations to their funding wallet in their repository's README. Although a deeper integration with a bot command etc could be interesting. 
   - For example, a community member opens a new issue and "funds" it by escrowing 1000 USD. Maybe we could spin up a SAFE that uses the project wallet, the community member's wallet, and a UbiquiBot wallet. It requires 2/3 signatures to move the funds. 
   - If the issue is closed as complete (according to the community member - not sure how to enforce this) then the payment automatically goes to the repository maintainer wallet.

> A software developer building an application needs four things: a browser, a terminal, an editor, and a package manager. Of these four, the package manager is what controls the tooling and frameworks a developer needs to construct their product. This layer is where we see the potential to change how open-source is secured and rewarded.

- They have deep technological experience in building these package managers. Their rewards structure seems to be based on the dependencies of software. Our rewards are all on GitHub.

- It seems that we have a more "micro" approach focusing on the internals of the active development of codebases. They are focused on the "macro" where they are focused on the reputation of entire software repositories and graphing them in dependency trees in the context of other repositories. 

> Transparency into the TEA tokens staked by community members to support each project enhances each project's reputation, much like the number of tokens a package maintainer stakes on their own work signals their commitment to it. These combined data points will help inform a reputation system for all community members and facilitate choice.

- The "financial" side is purely for TEA token staking for repository reputation. Digging deeper into this, its a cool idea to provide support for brand new, high quality projects. We could consider implementing something similar but on the stablecoin side, and on GitHub instead of within their platform (...unless?)

### Closing Remarks

Overall it is a cool idea. Their moat is their deep technological expertise in building package managers, and then building this graph/reputation system based on this tech stack for open source dependencies. They also have a pretty famous founder which is great for their fundraising and user growth.

**Comment by 0x4007** [comment] 2024-01-29 08:38
@sergfeldman as a heads up I closed this as complete to test our updated comment incentives tech. 

- It didn't include yours because your wallet isn't currently registered in our new database (I will migrate all of the wallet data soon.)
- Looks like it broke on evaluating the relevance of my comment probably due to its length. We need a more robust approach. 
- It would be helpful to link to the [GitHub Action run](https://github.com/ubiquibot/comment-incentives/actions/runs/7693245744/job/20961611371) while we wait for results.
- I am waiting to merge a pull request from whilefoo to fix the permit encoding format in the link (it requires a few small adjustments.)

**Comment by sergfeldman** [comment] 2024-01-29 19:39
> This is pretty insane. Good find.

@pavlovcik Wow, you wrote such a detailed analysis of the competitor! I'm glad you liked the find.

**Comment by sergfeldman** [comment] 2024-01-30 14:19
@pavlovcik Not sure the project is still maintained, but the logic in the code might be interesting https://github.com/sourcecred

**Comment by 0x4007** [comment] 2024-01-30 15:32
> @pavlovcik Not sure the project is still maintained, but the logic in the code might be interesting https://github.com/sourcecred

Looks like they shut down the crypto side. Everybody in the community returned their "grain" in April of 2022 according to their analytics

https://cred.sourcecred.io/#/explorer

I just realized that we could probably approach all of their contributors on their leaderboard to contribute to the DevPool once our updated infrastructure is more stable again. 

It is not clear to me what happened with them. They still retweet stuff, and there are some folks receiving cred still as of last week. Perhaps its now a side project of a couple of developers. I assume they don't have resources to scale this. 

They did a trial with MakerDAO apparently (https://github.com/sourcecred/makerdao-cred) and Yearn (https://github.com/sourcecred/yfi-cred) which makes a ton of sense according to the conversations I had (they seem to be really good fits for these types of systems.)

They really were ahead of their time. I'm curious to see precisely how it worked. I only understand it at a high level based on the materials I could find.

**Comment by sergfeldman** [comment] 2024-02-17 16:33
> @sergfeldman as a heads up I closed this as complete to test our updated comment incentives tech.
> 
> * It didn't include yours because your wallet isn't currently registered in our new database (I will migrate all of the wallet data soon.)
> * Looks like it broke on evaluating the relevance of my comment probably due to its length. We need a more robust approach.
> * It would be helpful to link to the [GitHub Action run](https://github.com/ubiquibot/comment-incentives/actions/runs/7693245744/job/20961611371) while we wait for results.
> * I am waiting to merge a pull request from whilefoo to fix the permit encoding format in the link (it requires a few small adjustments.)

@pavlovcik The bounty was not received due to technical issues.
Is it possible to get it?

**Comment by 0x4007** [comment] 2024-02-18 17:12
> ```diff
> ! Permit already posted
> ```

I've actually never seen this before in the latest version. 

Edit: I see it only is compatible with the old permit schema.

**Closed as completed** 2024-02-18 17:12 UTC

**Comment by 0x4007** [comment] 2024-02-18 17:13
As a heads up there is a bug with the relevance scoring not being applied right now.

**Comment by sergfeldman** [comment] 2024-02-19 21:46
Thank you, claimed.
